package com.abc.daos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import com.abc.connectiondb.ConnectionDB;
import com.abc.model.ProductModel;
import com.abc.model.UserModel;
import com.abc.model.UserTypeModel;

public class UserDAO {

	Connection conn = null;
	Statement stmt = null;

	public ArrayList<UserTypeModel> getUserList() {
		return null;
	}

	public void createUser(UserModel user) {
		int autoGeneratedID;
		try {
			conn = ConnectionDB.getConnection();
			stmt = conn.createStatement();
			String sql = "insert into users (id, user_name, password, type, status, created_date) "
					+ " values ( "
					+ user.getId()
					+ ",'"
					+ user.getUserName()
					+ "','"
					+ user.getPassword()
					+ "','"
					+ user.getUserType().getId()
					+ "','"
					+ user.getStatus()
					+ "','"
					+ new java.sql.Date(System.currentTimeMillis()) + "')";

			PreparedStatement pstmt = conn.prepareStatement(sql,
					Statement.RETURN_GENERATED_KEYS);
			pstmt.executeUpdate();
			ResultSet keys = pstmt.getGeneratedKeys();
			keys.next();
			autoGeneratedID = keys.getInt(1);
			user.setId(autoGeneratedID);
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			// finally block used to close resources
			try {
				if (stmt != null)
					conn.close();
			} catch (SQLException se) {
			}// do nothing
			try {
				if (conn != null)
					conn.close();
			} catch (SQLException se) {
				se.printStackTrace();
			}// end finally try
		}

	}

	public UserModel getUser(UserModel user) {
		ResultSet rs = null;
		UserModel getUser = null;
		try {
			conn = ConnectionDB.getConnection();
			stmt = conn.createStatement();
			String sql = "select * from users where id = " + user.getId();

			rs = stmt.executeQuery(sql);
			if (rs.next()) {
				getUser = new UserModel(rs.getInt("id"), rs.getInt("type"),
						rs.getString("user_name"), rs.getString("password"),
						rs.getInt("status"));
			}

		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			// finally block used to close resources
			try {
				if (stmt != null)
					conn.close();
			} catch (SQLException se) {
			}// do nothing
			try {
				if (conn != null)
					conn.close();
			} catch (SQLException se) {
				se.printStackTrace();
			}// end finally try
		}

		return getUser;
	}

}
